<a href="https://colab.research.google.com/github/genevievemacabio/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROBLEM 1**

In [5]:
import numpy as np
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)

print(amt)

[[13.]
 [57.]
 [19.]]


**PROBLEM 2**

In [2]:
import numpy as np
from scipy.linalg import solve
A = np.array([[3, -1, 1],[9, -3, 3],[-12, 4, -4]])
print(A)
print()
B = np.array([[5],[15],[-20]])
print(B)
print()
X = solve(A,B)
print(X)


[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

[[  5]
 [ 15]
 [-20]]



LinAlgError: ignored

*The code fails due to the singularity of the matrix, which implies that there is no unique solution: either none or infinite, depending on the constants used.*

**PROBLEM 3**

In [1]:
import numpy as np
from numpy.linalg import eig #Compute the eigenvalues and right eigenvectors of a square array
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A)
print("Eigenvalues:",w)
print("Eigenvectors:",v)

x = v.round()
print(x)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
Eigenvalues: [-1.  3.  2.]
Eigenvectors: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.24992575e-15]
 [-3.01511345e-01 -2.31918026e-15  7.07106781e-01]]
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
