<a href="https://colab.research.google.com/github/genevievemacabio/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5

In [24]:
import numpy as np #import Library
#square matrix has same length and width thus it is 5x5 matrix

SquareMatrix = np.array ([[6,0,0,0,6],[7,0,0,0,7],[8,0,0,0,8],[9,0,0,0,9],[4,0,0,0,4]]) #5x5 matrix

print("SQUARE MATRIX WHOSE LENGTH IS 5:") 
print() 
print(SquareMatrix) #displays the final output


SQUARE MATRIX WHOSE LENGTH IS 5:

[[6 0 0 0 6]
 [7 0 0 0 7]
 [8 0 0 0 8]
 [9 0 0 0 9]
 [4 0 0 0 4]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [21]:
A = np.triu([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]) #square matrix
print(A) #displays the final output

[[1 2 3 4 5]
 [0 2 3 4 5]
 [0 0 3 4 5]
 [0 0 0 4 5]
 [0 0 0 0 5]]


Question 3. Create a Python code that displays a square matrix which is symmetrical 

In [26]:
C = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #square matrix

print("SQUARE MATRIX WHICH IS SYMMETRICAL:")
print(C) #displays the final output

SQUARE MATRIX WHICH IS SYMMETRICAL:
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding.

In [12]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]]) #Given matrix

invC = np.linalg.inv(C) #Compute the (multiplicative) inverse of a matrix

print("INVERSE OF MATRIX C:")
print(invC) #displays the final output

INVERSE OF MATRIX C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [10]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]]) #Given matrix

detOfC = np.linalg.det(C) #Compute the determinant of an array

print("DETERMINANT OF THE GIVEN MATRIX IN QUESTION 4:")
print(int(detOfC)) #displays the final output

DETERMINANT OF THE GIVEN MATRIX IN QUESTION 4:
5


Question 6. Find the roots of the linear equations by showing its python codes 


In [9]:
eq= np.array([[5,4,1],[10,9,4], [10,13,15]]) #Given matrix

const = np.array([[[3.4],[8.8],[19.2]]])

roots = np.linalg.inv(eq) @ const

print("ROOTS OF THE GIVEN LINEAR EQUATIONS:")
print(roots) #displays the final output

ROOTS OF THE GIVEN LINEAR EQUATIONS:
[[[0.2]
  [0.4]
  [0.8]]]
