<a href="https://colab.research.google.com/github/genevievemacabio/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question #1 Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C".

In [6]:
#Matrix C

import numpy as np
C = np.eye(4)
print (C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question #2  In relation to Question 1, show a solution that doubles all the values of each element.

In [5]:
import numpy as np
C = np.eye(4) * 2
print (C)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question #3 Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8].

In [3]:
A = np.array([2,7,4])
B = np.array([3,9,8])
cross = np.cross(A,B)
print(cross)

[20 -4 -3]
