<a href="https://colab.research.google.com/github/genevievemacabio/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [4]:
import numpy as np
A = np.array([[-5,0],[4,1,]]) #This is Matrix A
print(A)
B = np.array([[6,-3],[2,3]]) #This is Matrix B
print(B)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [6]:
import numpy as np
A = np.array([[-5,0],[4,1,]])
B = np.array([[6,-3],[2,3]])
print(A+B) #This is the sum of A & B


[[ 1 -3]
 [ 6  4]]


In [7]:
import numpy as np
A = np.array([[-5,0],[4,1,]])
B = np.array([[6,-3],[2,3]])
print(B-A) #This is the difference1

[[11 -3]
 [-2  2]]


In [8]:
import numpy as np
A = np.array([[-5,0],[4,1,]])
B = np.array([[6,-3],[2,3]])
print(A-B) #This is the difference2

[[-11   3]
 [  2  -2]]
